# Generated by Django 3.2.3 on 2021-05-30 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdcleague', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team1', models.CharField(max_length=120)),
                ('team2', models.CharField(max_length=120)),
                ('mapType', models.CharField(max_length=120)),
                ('pickType', models.CharField(max_length=120)),
                ('count', models.IntegerField()),
                ('tournamentCodes', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='Sdcleague',
        ),
    ]
