# Generated by Django 3.2.3 on 2021-06-05 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sdcleague', '0003_game_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='tournamentCodes',
        ),
    ]
