# Generated by Django 3.2.3 on 2021-06-05 21:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdcleague', '0004_remove_game_tournamentcodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='count',
            field=models.IntegerField(default=3, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='game',
            name='mapType',
            field=models.CharField(choices=[('SUMMONERS_RIFT', 'Summoners Rift'), ('TWISTED_TREELINE', 'Twisted Treeline'), ('HOWLING_ABYSS', 'Howling Abyss')], max_length=120),
        ),
        migrations.AlterField(
            model_name='game',
            name='pickType',
            field=models.CharField(choices=[('BLIND_PICK', 'Blind Pick'), ('DRAFT_MODE', 'Draft Pick'), ('ALL_RANDOM', 'All Random'), ('TOURNAMENT_DRAFT', 'Tournament Draft')], max_length=120),
        ),
    ]
