# Generated by Django 3.2.4 on 2021-06-05 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sdcleague', '0005_auto_20210605_1706'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='tournamentCodes',
            field=models.CharField(default='not generated', max_length=240),
        ),
    ]
